name: CodeNotes

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/formatting@v2

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/linting@v2

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/build@v2
